# If build passes tests, push to release CR
docker-build:
  stage: docker-build
  image: yodascholtz/nix-build-env:latest
  services:
    - docker:dind
  variables:
    PROJECT_NAME: $CI_PROJECT_NAME
    BRANCH_NAME: $CI_BUILD_REF_NAME
  script:
    - .environments/deployment/build.sh
  only:
    - nightly

deploy:
  stage: deploy
  environment: production
  image: yodascholtz/nix-build-env:latest
  variables:
    CLUSTER: AmazonEKS_LinumLabs_Spot
    PROJECT_NAME: $CI_PROJECT_NAME
    BRANCH_NAME: $CI_BUILD_REF_NAME
  script:
    - nix-shell .environments/derivation_shell.nix/shell.drv
    - .environments/scripts/configure-k8s.sh
    - .environments/deployment/deploy.sh
  only:
    - nightly
