version: '3.5'
services:
  core:
    image: $REGISTRY/linumlabs/molecule-alpha/build/core:latest
    build:
      context: .
      dockerfile: ./Dockerfile.core
  builder:
    image: $REGISTRY/linumlabs/molecule-alpha/build/builder:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - API_HOST
        - API_SCHEMA
        - APM_SERVICE_NAME
        - APM_SERVER_ENDPOINT
        - APP_NAME
        - APP_SCHEMA
        - APP_HOST
        - APP_PORT
        - MAINNET_DAI_ADDRESS
        - GOERLI_DAI_ADDRESS
        - RINKEBY_DAI_ADDRESS
        - KOVAN_DAI_ADDRESS
        - ROPSTEN_DAI_ADDRESS
        - PDAI_CONTRACT_ADDRESS
        - MARKET_REGISTRY_ADDRESS
        - MARKET_FACTORY_ADDRESS
    depends_on:
      - core
  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --smallfiles --logpath=/dev/null
  apiserver:
    image: $MOLECULE_BACKEND_CONTAINER_RELEASE_IMAGE
    build:
      context: .
      dockerfile: ./ApiServer/Dockerfile
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo
      - builder
    ports:
      - 3001:3001
    links:
      - mongo
  webapp:
    image: $MOLECULE_FRONTEND_CONTAINER_RELEASE_IMAGE
    build:
      context: .
      dockerfile: ./WebApp/Dockerfile
    depends_on:
      - apiserver
      - builder
    ports:
      - 3000:80
    links:
      - apiserver
volumes:
    mongodb:
